name: matchcut
channels:
  - pytorch
  - defaults
  - conda-forge
  - intel
dependencies:
  - python==3.7.4
  - pip==20.2.4
  - scikit-learn==0.24.2
  - pandas==1.3.4
  - numpy==1.19.5
  - pytorch==1.10.0
  - toolz==0.10.0
  - pip:
      - xgboost==1.2.1
      - pytorch-metric-learning==0.9.99
      - scipy==1.5.4
